#ifndef MQTT_CONNECTION_CONFIG_H
#define MQTT_CONNECTION_CONFIG_H

#define WIFI_SSID "vodafoneEF3A"
#define WIFI_PASS "U3AJ6EXDSZ935M"
#define MQTT_BROKER "192.168.0.14"
#define MQTT_PORT 1884

#endif
